import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateAuthSchema1786644000000 implements MigrationInterface {
  name = 'CreateAuthSchema1786644000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE auth_permissions (
        code varchar(80) PRIMARY KEY,
        name varchar(120) NOT NULL
      )
    `);
    await queryRunner.query(`
      CREATE TABLE auth_roles (
        code varchar(30) PRIMARY KEY,
        name varchar(80) NOT NULL,
        description varchar(300) NOT NULL,
        editable boolean NOT NULL DEFAULT true
      )
    `);
    await queryRunner.query(`
      CREATE TABLE auth_users (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username varchar(50) NOT NULL,
        full_name varchar(150) NOT NULL,
        password_hash varchar(255) NOT NULL,
        status varchar(10) NOT NULL DEFAULT 'Activo',
        primary_role_code varchar(30) NOT NULL,
        registered_at timestamptz NOT NULL DEFAULT now(),
        last_access timestamptz NULL,
        CONSTRAINT ck_auth_users_status CHECK (status IN ('Activo', 'Inactivo')),
        CONSTRAINT fk_auth_users_primary_role
          FOREIGN KEY (primary_role_code) REFERENCES auth_roles(code) ON DELETE RESTRICT
      )
    `);
    await queryRunner.query(
      'CREATE UNIQUE INDEX ux_auth_users_username_lower ON auth_users (LOWER(username))',
    );
    await queryRunner.query(`
      CREATE TABLE auth_role_permissions (
        role_code varchar(30) NOT NULL,
        permission_code varchar(80) NOT NULL,
        PRIMARY KEY (role_code, permission_code),
        FOREIGN KEY (role_code) REFERENCES auth_roles(code) ON DELETE CASCADE,
        FOREIGN KEY (permission_code) REFERENCES auth_permissions(code) ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`
      CREATE TABLE auth_user_roles (
        user_id integer NOT NULL,
        role_code varchar(30) NOT NULL,
        PRIMARY KEY (user_id, role_code),
        FOREIGN KEY (user_id) REFERENCES auth_users(id) ON DELETE CASCADE,
        FOREIGN KEY (role_code) REFERENCES auth_roles(code) ON DELETE RESTRICT
      )
    `);
    await queryRunner.query(`
      CREATE TABLE auth_user_permissions (
        user_id integer NOT NULL,
        permission_code varchar(80) NOT NULL,
        PRIMARY KEY (user_id, permission_code),
        FOREIGN KEY (user_id) REFERENCES auth_users(id) ON DELETE CASCADE,
        FOREIGN KEY (permission_code) REFERENCES auth_permissions(code) ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`
      CREATE TABLE auth_refresh_sessions (
        id uuid PRIMARY KEY,
        user_id integer NOT NULL,
        token_hash char(64) NOT NULL UNIQUE,
        created_at timestamptz NOT NULL,
        expires_at timestamptz NOT NULL,
        revoked_at timestamptz NULL,
        replaced_by_session_id uuid NULL,
        user_agent varchar(300) NULL,
        ip_address varchar(64) NULL,
        FOREIGN KEY (user_id) REFERENCES auth_users(id) ON DELETE CASCADE
      )
    `);
    await queryRunner.query(
      'CREATE INDEX ix_auth_refresh_sessions_user_id ON auth_refresh_sessions(user_id)',
    );
    await queryRunner.query(
      'CREATE INDEX ix_auth_refresh_sessions_expires_at ON auth_refresh_sessions(expires_at)',
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS auth_refresh_sessions');
    await queryRunner.query('DROP TABLE IF EXISTS auth_user_permissions');
    await queryRunner.query('DROP TABLE IF EXISTS auth_user_roles');
    await queryRunner.query('DROP TABLE IF EXISTS auth_role_permissions');
    await queryRunner.query('DROP TABLE IF EXISTS auth_users');
    await queryRunner.query('DROP TABLE IF EXISTS auth_roles');
    await queryRunner.query('DROP TABLE IF EXISTS auth_permissions');
  }
}
