import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateSalesCashSchema1786874400000 implements MigrationInterface {
  name = 'CreateSalesCashSchema1786874400000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE SEQUENCE ops_order_number_seq START 1`);
    await queryRunner.query(`
      CREATE TABLE ops_cash_sessions (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        status varchar(10) NOT NULL DEFAULT 'Abierta',
        opening_user_id integer NOT NULL,
        opening_user_name varchar(120) NOT NULL,
        initial_amount numeric(12,2) NOT NULL,
        opening_note varchar(300) NULL,
        opened_at timestamptz NOT NULL DEFAULT now(),
        closing_user_id integer NULL,
        closing_user_name varchar(120) NULL,
        counted_amount numeric(12,2) NULL,
        expected_cash numeric(12,2) NULL,
        difference numeric(12,2) NULL,
        closing_note varchar(300) NULL,
        closed_at timestamptz NULL,
        CONSTRAINT ck_ops_cash_sessions_status CHECK (status IN ('Abierta','Cerrada')),
        CONSTRAINT ck_ops_cash_sessions_initial_amount CHECK (initial_amount >= 0)
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX ux_ops_cash_sessions_user_open ON ops_cash_sessions(opening_user_id) WHERE status = 'Abierta'`,
    );

    await queryRunner.query(`
      CREATE TABLE ops_sales (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_number varchar(20) NOT NULL UNIQUE,
        sales_channel varchar(20) NOT NULL,
        pedidosya_reference varchar(100) NULL,
        pedidosya_settlement_id integer NULL,
        pedidosya_settled_at timestamptz NULL,
        client_type varchar(30) NOT NULL,
        client_id integer NULL,
        client_name varchar(120) NOT NULL,
        registered_by_user_id integer NOT NULL,
        registered_by_user_name varchar(120) NOT NULL,
        registration_cash_session_id integer NOT NULL,
        observations varchar(500) NULL,
        requires_preparation boolean NOT NULL,
        subtotal numeric(12,2) NOT NULL,
        discount_type varchar(20) NOT NULL DEFAULT 'Ninguno',
        discount_value numeric(12,2) NOT NULL DEFAULT 0,
        discount_amount numeric(12,2) NOT NULL DEFAULT 0,
        discount_reason varchar(200) NULL,
        total numeric(12,2) NOT NULL,
        preparation_status varchar(30) NOT NULL,
        payment_status varchar(30) NOT NULL,
        last_payment_id integer NULL,
        accumulated_payment_method varchar(20) NULL,
        cancellation_reason varchar(200) NULL,
        registered_at timestamptz NOT NULL DEFAULT now(),
        preparation_started_at timestamptz NULL,
        ready_at timestamptz NULL,
        delivered_at timestamptz NULL,
        delivered_by_user_id integer NULL,
        delivered_by_user_name varchar(120) NULL,
        delivery_cash_session_id integer NULL,
        fully_paid_at timestamptz NULL,
        cancelled_at timestamptz NULL,
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT fk_ops_sales_client FOREIGN KEY (client_id) REFERENCES ops_clients(id) ON DELETE RESTRICT,
        CONSTRAINT fk_ops_sales_registration_cash FOREIGN KEY (registration_cash_session_id) REFERENCES ops_cash_sessions(id) ON DELETE RESTRICT,
        CONSTRAINT fk_ops_sales_delivery_cash FOREIGN KEY (delivery_cash_session_id) REFERENCES ops_cash_sessions(id) ON DELETE RESTRICT,
        CONSTRAINT ck_ops_sales_channel CHECK (sales_channel IN ('Local','PedidosYa')),
        CONSTRAINT ck_ops_sales_client_type CHECK (client_type IN ('Consumidor final','Registrado','Ocasional')),
        CONSTRAINT ck_ops_sales_discount_type CHECK (discount_type IN ('Ninguno','Porcentaje','Monto fijo')),
        CONSTRAINT ck_ops_sales_preparation_status CHECK (preparation_status IN ('En cola','En preparación','Entrega directa','Listo','Entregado','Anulado')),
        CONSTRAINT ck_ops_sales_payment_status CHECK (payment_status IN ('Pendiente de cobro','Cobrada','Pendiente de liquidación','Liquidada','Anulada')),
        CONSTRAINT ck_ops_sales_amounts CHECK (subtotal > 0 AND total > 0 AND total <= subtotal),
        CONSTRAINT ck_ops_sales_pedidosya_reference CHECK ((sales_channel = 'Local' AND pedidosya_reference IS NULL) OR (sales_channel = 'PedidosYa' AND pedidosya_reference IS NOT NULL))
      )
    `);
    await queryRunner.query(
      `CREATE INDEX ix_ops_sales_registered_at ON ops_sales(registered_at DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX ix_ops_sales_preparation_status ON ops_sales(preparation_status)`,
    );
    await queryRunner.query(
      `CREATE INDEX ix_ops_sales_payment_status ON ops_sales(payment_status)`,
    );

    await queryRunner.query(`
      CREATE TABLE ops_sale_details (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_id integer NOT NULL,
        product_id integer NOT NULL,
        product_code varchar(20) NOT NULL,
        product_name varchar(120) NOT NULL,
        unit_price numeric(12,2) NOT NULL,
        quantity integer NOT NULL,
        note varchar(300) NULL,
        subtotal numeric(12,2) NOT NULL,
        requires_preparation boolean NOT NULL,
        CONSTRAINT fk_ops_sale_details_sale FOREIGN KEY (sale_id) REFERENCES ops_sales(id) ON DELETE CASCADE,
        CONSTRAINT fk_ops_sale_details_product FOREIGN KEY (product_id) REFERENCES ops_products(id) ON DELETE RESTRICT,
        CONSTRAINT ck_ops_sale_details_quantity CHECK (quantity > 0 AND quantity <= 100),
        CONSTRAINT ck_ops_sale_details_amounts CHECK (unit_price > 0 AND subtotal > 0)
      )
    `);
    await queryRunner.query(`CREATE INDEX ix_ops_sale_details_sale ON ops_sale_details(sale_id)`);

    await queryRunner.query(`
      CREATE TABLE ops_sale_payments (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cash_session_id integer NOT NULL,
        sale_id integer NOT NULL,
        order_number varchar(20) NOT NULL,
        subtotal numeric(12,2) NOT NULL,
        discount_type varchar(20) NOT NULL,
        discount_value numeric(12,2) NOT NULL,
        discount_amount numeric(12,2) NOT NULL,
        discount_reason varchar(200) NULL,
        sale_total numeric(12,2) NOT NULL,
        applied_amount numeric(12,2) NOT NULL,
        payment_method varchar(20) NOT NULL,
        cash_amount numeric(12,2) NOT NULL,
        qr_amount numeric(12,2) NOT NULL,
        received_amount numeric(12,2) NOT NULL,
        change_amount numeric(12,2) NOT NULL,
        qr_reference varchar(100) NULL,
        user_id integer NOT NULL,
        user_name varchar(120) NOT NULL,
        paid_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT fk_ops_sale_payments_cash FOREIGN KEY (cash_session_id) REFERENCES ops_cash_sessions(id) ON DELETE RESTRICT,
        CONSTRAINT fk_ops_sale_payments_sale FOREIGN KEY (sale_id) REFERENCES ops_sales(id) ON DELETE RESTRICT,
        CONSTRAINT ck_ops_sale_payments_method CHECK (payment_method IN ('Efectivo','QR','Mixto')),
        CONSTRAINT ck_ops_sale_payments_amounts CHECK (applied_amount > 0 AND cash_amount >= 0 AND qr_amount >= 0 AND applied_amount = cash_amount + qr_amount)
      )
    `);
    await queryRunner.query(`CREATE INDEX ix_ops_sale_payments_sale ON ops_sale_payments(sale_id)`);
    await queryRunner.query(
      `CREATE INDEX ix_ops_sale_payments_cash ON ops_sale_payments(cash_session_id)`,
    );

    await queryRunner.query(`
      CREATE TABLE ops_cash_movements (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cash_session_id integer NOT NULL,
        type varchar(10) NOT NULL,
        concept varchar(160) NOT NULL,
        amount numeric(12,2) NOT NULL,
        cash_amount numeric(12,2) NOT NULL,
        qr_amount numeric(12,2) NOT NULL,
        payment_method varchar(20) NULL,
        sale_id integer NULL,
        order_number varchar(20) NULL,
        user_id integer NOT NULL,
        user_name varchar(120) NOT NULL,
        registered_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT fk_ops_cash_movements_cash FOREIGN KEY (cash_session_id) REFERENCES ops_cash_sessions(id) ON DELETE RESTRICT,
        CONSTRAINT fk_ops_cash_movements_sale FOREIGN KEY (sale_id) REFERENCES ops_sales(id) ON DELETE RESTRICT,
        CONSTRAINT ck_ops_cash_movements_type CHECK (type IN ('Venta','Ingreso','Egreso')),
        CONSTRAINT ck_ops_cash_movements_method CHECK (payment_method IS NULL OR payment_method IN ('Efectivo','QR','Mixto')),
        CONSTRAINT ck_ops_cash_movements_amounts CHECK (amount > 0 AND cash_amount >= 0 AND qr_amount >= 0)
      )
    `);
    await queryRunner.query(
      `CREATE INDEX ix_ops_cash_movements_cash ON ops_cash_movements(cash_session_id, registered_at)`,
    );

    await queryRunner.query(`
      CREATE TABLE ops_settings (
        key varchar(80) PRIMARY KEY,
        value varchar(200) NOT NULL,
        updated_at timestamptz NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(
      `INSERT INTO ops_settings(key, value) VALUES ('preparation_start_mode', 'En preparación')`,
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS ops_cash_movements');
    await queryRunner.query('DROP TABLE IF EXISTS ops_sale_payments');
    await queryRunner.query('DROP TABLE IF EXISTS ops_sale_details');
    await queryRunner.query('DROP TABLE IF EXISTS ops_sales');
    await queryRunner.query('DROP TABLE IF EXISTS ops_cash_sessions');
    await queryRunner.query('DROP TABLE IF EXISTS ops_settings');
    await queryRunner.query('DROP SEQUENCE IF EXISTS ops_order_number_seq');
  }
}
