import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateCatalogSchema1786788000000 implements MigrationInterface {
  name = 'CreateCatalogSchema1786788000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE ops_categories (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(100) NOT NULL,
        description varchar(300) NOT NULL,
        status varchar(10) NOT NULL DEFAULT 'Activo',
        registered_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT ck_ops_categories_status CHECK (status IN ('Activo', 'Inactivo'))
      )
    `);
    await queryRunner.query(
      'CREATE UNIQUE INDEX ux_ops_categories_name_lower ON ops_categories (LOWER(name))',
    );

    await queryRunner.query(`
      CREATE TABLE ops_products (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code varchar(20) NOT NULL,
        name varchar(120) NOT NULL,
        description varchar(500) NOT NULL,
        category_id integer NOT NULL,
        price numeric(12,2) NOT NULL,
        available_pedidosya boolean NOT NULL DEFAULT false,
        pedidosya_price numeric(12,2) NULL,
        status varchar(10) NOT NULL DEFAULT 'Activo',
        available boolean NOT NULL DEFAULT true,
        featured boolean NOT NULL DEFAULT false,
        preparation_mode varchar(30) NOT NULL DEFAULT 'Requiere preparación',
        inventory_control varchar(30) NOT NULL DEFAULT 'Con receta',
        image_url varchar(500) NULL,
        registered_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT fk_ops_products_category
          FOREIGN KEY (category_id) REFERENCES ops_categories(id) ON DELETE RESTRICT,
        CONSTRAINT ck_ops_products_price CHECK (price > 0 AND price <= 100000),
        CONSTRAINT ck_ops_products_pedidosya_price
          CHECK ((available_pedidosya = false AND pedidosya_price IS NULL) OR
                 (available_pedidosya = true AND pedidosya_price > 0 AND pedidosya_price <= 100000)),
        CONSTRAINT ck_ops_products_status CHECK (status IN ('Activo', 'Inactivo')),
        CONSTRAINT ck_ops_products_preparation_mode
          CHECK (preparation_mode IN ('Requiere preparación', 'Entrega directa')),
        CONSTRAINT ck_ops_products_inventory_control
          CHECK (inventory_control IN ('Con receta', 'No controla inventario'))
      )
    `);
    await queryRunner.query(
      'CREATE UNIQUE INDEX ux_ops_products_code_lower ON ops_products (LOWER(code))',
    );
    await queryRunner.query(
      'CREATE UNIQUE INDEX ux_ops_products_name_category ON ops_products (category_id, LOWER(name))',
    );
    await queryRunner.query(
      'CREATE INDEX ix_ops_products_category_id ON ops_products(category_id)',
    );

    await queryRunner.query(`
      CREATE TABLE ops_clients (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name varchar(120) NOT NULL,
        document_type varchar(20) NULL,
        document_number varchar(30) NULL,
        phone varchar(20) NULL,
        email varchar(120) NULL,
        address varchar(220) NULL,
        zone varchar(100) NULL,
        address_reference varchar(180) NULL,
        location_url varchar(500) NULL,
        delivery_instructions varchar(300) NULL,
        observations varchar(300) NULL,
        status varchar(10) NOT NULL DEFAULT 'Activo',
        archived boolean NOT NULL DEFAULT false,
        archived_at timestamptz NULL,
        registered_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT ck_ops_clients_status CHECK (status IN ('Activo', 'Inactivo')),
        CONSTRAINT ck_ops_clients_document_type
          CHECK (document_type IS NULL OR document_type IN ('CI', 'NIT', 'Pasaporte', 'Otro')),
        CONSTRAINT ck_ops_clients_document_pair
          CHECK ((document_type IS NULL AND document_number IS NULL) OR
                 (document_type IS NOT NULL AND document_number IS NOT NULL))
      )
    `);
    await queryRunner.query(
      'CREATE UNIQUE INDEX ux_ops_clients_document_upper ON ops_clients (UPPER(document_number)) WHERE document_number IS NOT NULL',
    );
    await queryRunner.query('CREATE INDEX ix_ops_clients_full_name ON ops_clients(full_name)');
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS ops_clients');
    await queryRunner.query('DROP TABLE IF EXISTS ops_products');
    await queryRunner.query('DROP TABLE IF EXISTS ops_categories');
  }
}
