import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateInventorySchema1786960800000 implements MigrationInterface {
  name = 'CreateInventorySchema1786960800000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE inv_ingredients (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code varchar(30) NOT NULL,
        name varchar(120) NOT NULL,
        category varchar(80) NOT NULL,
        base_unit varchar(10) NOT NULL,
        purchase_presentation varchar(60) NOT NULL,
        purchase_conversion_factor numeric(16,4) NOT NULL,
        stock numeric(16,4) NOT NULL DEFAULT 0,
        low_stock_control boolean NOT NULL DEFAULT true,
        minimum_stock numeric(16,4) NOT NULL DEFAULT 0,
        shortage_policy varchar(40) NOT NULL,
        economic_control boolean NOT NULL DEFAULT false,
        average_base_unit_cost numeric(16,6) NULL,
        status varchar(10) NOT NULL DEFAULT 'Activo',
        registered_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        updated_by_user_id integer NOT NULL,
        updated_by_user_name varchar(120) NOT NULL,
        CONSTRAINT ck_inv_ingredients_base_unit CHECK (base_unit IN ('g','ml','unidad')),
        CONSTRAINT ck_inv_ingredients_shortage_policy CHECK (shortage_policy IN ('Permitir con advertencia','Bloquear')),
        CONSTRAINT ck_inv_ingredients_status CHECK (status IN ('Activo','Inactivo')),
        CONSTRAINT ck_inv_ingredients_conversion CHECK (purchase_conversion_factor > 0),
        CONSTRAINT ck_inv_ingredients_minimum CHECK (minimum_stock >= 0),
        CONSTRAINT ck_inv_ingredients_cost CHECK ((economic_control = false AND average_base_unit_cost IS NULL) OR (economic_control = true AND (average_base_unit_cost IS NULL OR average_base_unit_cost >= 0)))
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX ux_inv_ingredients_code_lower ON inv_ingredients(LOWER(code))`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX ux_inv_ingredients_name_lower ON inv_ingredients(LOWER(name))`,
    );

    await queryRunner.query(`
      CREATE TABLE inv_product_refs (
        product_id integer PRIMARY KEY,
        code varchar(20) NOT NULL,
        name varchar(120) NOT NULL,
        inventory_control varchar(30) NOT NULL,
        status varchar(10) NOT NULL,
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT ck_inv_product_refs_control CHECK (inventory_control IN ('Con receta','No controla inventario')),
        CONSTRAINT ck_inv_product_refs_status CHECK (status IN ('Activo','Inactivo'))
      )
    `);

    await queryRunner.query(`
      CREATE TABLE inv_recipes (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id integer NOT NULL,
        product_code varchar(20) NOT NULL,
        product_name varchar(120) NOT NULL,
        version integer NOT NULL,
        status varchar(12) NOT NULL,
        valid_from timestamptz NOT NULL DEFAULT now(),
        valid_until timestamptz NULL,
        registered_by_user_id integer NOT NULL,
        registered_by_user_name varchar(120) NOT NULL,
        CONSTRAINT ck_inv_recipes_status CHECK (status IN ('Vigente','Histórica')),
        CONSTRAINT ck_inv_recipes_version CHECK (version > 0),
        CONSTRAINT ux_inv_recipes_product_version UNIQUE(product_id, version)
      )
    `);
    await queryRunner.query(
      `CREATE UNIQUE INDEX ux_inv_recipes_current ON inv_recipes(product_id) WHERE status = 'Vigente'`,
    );

    await queryRunner.query(`
      CREATE TABLE inv_recipe_items (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        recipe_id integer NOT NULL,
        ingredient_id integer NOT NULL,
        quantity_per_product numeric(16,4) NOT NULL,
        CONSTRAINT fk_inv_recipe_items_recipe FOREIGN KEY (recipe_id) REFERENCES inv_recipes(id) ON DELETE CASCADE,
        CONSTRAINT fk_inv_recipe_items_ingredient FOREIGN KEY (ingredient_id) REFERENCES inv_ingredients(id) ON DELETE RESTRICT,
        CONSTRAINT ck_inv_recipe_items_quantity CHECK (quantity_per_product > 0),
        CONSTRAINT ux_inv_recipe_items_recipe_ingredient UNIQUE(recipe_id, ingredient_id)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE inv_movements (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ingredient_id integer NOT NULL,
        ingredient_code varchar(30) NOT NULL,
        ingredient_name varchar(120) NOT NULL,
        base_unit varchar(10) NOT NULL,
        type varchar(40) NOT NULL,
        origin varchar(30) NOT NULL,
        quantity numeric(16,4) NOT NULL,
        classified_quantity numeric(16,4) NULL,
        previous_stock numeric(16,4) NOT NULL,
        resulting_stock numeric(16,4) NOT NULL,
        reason varchar(220) NOT NULL,
        reference varchar(120) NULL,
        sale_id integer NULL,
        order_number varchar(20) NULL,
        recipe_version_ids integer[] NOT NULL DEFAULT '{}',
        applied_unit_cost numeric(16,6) NULL,
        economic_impact numeric(14,2) NULL,
        registered_at timestamptz NOT NULL DEFAULT now(),
        user_id integer NOT NULL,
        user_name varchar(120) NOT NULL,
        CONSTRAINT fk_inv_movements_ingredient FOREIGN KEY (ingredient_id) REFERENCES inv_ingredients(id) ON DELETE RESTRICT
      )
    `);
    await queryRunner.query(
      `CREATE INDEX ix_inv_movements_ingredient_date ON inv_movements(ingredient_id, registered_at DESC)`,
    );
    await queryRunner.query(
      `CREATE INDEX ix_inv_movements_sale ON inv_movements(sale_id) WHERE sale_id IS NOT NULL`,
    );

    await queryRunner.query(`
      CREATE TABLE inv_sale_consumptions (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_id integer NOT NULL UNIQUE,
        order_number varchar(20) NOT NULL,
        status varchar(40) NOT NULL,
        authorized_negative_balance boolean NOT NULL DEFAULT false,
        registered_at timestamptz NOT NULL DEFAULT now(),
        treatment_at timestamptz NULL,
        cancellation_treatment varchar(40) NULL,
        treatment_reason varchar(220) NULL,
        registered_by_user_id integer NOT NULL,
        registered_by_user_name varchar(120) NOT NULL,
        treatment_by_user_id integer NULL,
        treatment_by_user_name varchar(120) NULL,
        CONSTRAINT ck_inv_sale_consumptions_status CHECK (status IN ('Aplicado','Reintegrado','Clasificado como merma')),
        CONSTRAINT ck_inv_sale_consumptions_treatment CHECK (cancellation_treatment IS NULL OR cancellation_treatment IN ('Reintegrar insumos','Registrar como merma'))
      )
    `);

    await queryRunner.query(`
      CREATE TABLE inv_sale_consumption_details (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        consumption_id integer NOT NULL,
        ingredient_id integer NOT NULL,
        ingredient_code varchar(30) NOT NULL,
        ingredient_name varchar(120) NOT NULL,
        base_unit varchar(10) NOT NULL,
        consumed_quantity numeric(16,4) NOT NULL,
        previous_stock numeric(16,4) NOT NULL,
        resulting_stock numeric(16,4) NOT NULL,
        applied_unit_cost numeric(16,6) NULL,
        applied_total_cost numeric(14,2) NULL,
        recipe_version_ids integer[] NOT NULL DEFAULT '{}',
        related_products text[] NOT NULL DEFAULT '{}',
        CONSTRAINT fk_inv_consumption_details_consumption FOREIGN KEY (consumption_id) REFERENCES inv_sale_consumptions(id) ON DELETE CASCADE,
        CONSTRAINT fk_inv_consumption_details_ingredient FOREIGN KEY (ingredient_id) REFERENCES inv_ingredients(id) ON DELETE RESTRICT,
        CONSTRAINT ck_inv_consumption_details_quantity CHECK (consumed_quantity > 0)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE inv_counts (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        observations varchar(400) NULL,
        registered_at timestamptz NOT NULL DEFAULT now(),
        user_id integer NOT NULL,
        user_name varchar(120) NOT NULL
      )
    `);

    await queryRunner.query(`
      CREATE TABLE inv_count_details (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        count_id integer NOT NULL,
        ingredient_id integer NOT NULL,
        ingredient_code varchar(30) NOT NULL,
        ingredient_name varchar(120) NOT NULL,
        base_unit varchar(10) NOT NULL,
        theoretical_stock numeric(16,4) NOT NULL,
        physical_stock numeric(16,4) NOT NULL,
        variation numeric(16,4) NOT NULL,
        reason varchar(220) NOT NULL,
        applied_unit_cost numeric(16,6) NULL,
        economic_impact numeric(14,2) NULL,
        CONSTRAINT fk_inv_count_details_count FOREIGN KEY (count_id) REFERENCES inv_counts(id) ON DELETE CASCADE,
        CONSTRAINT fk_inv_count_details_ingredient FOREIGN KEY (ingredient_id) REFERENCES inv_ingredients(id) ON DELETE RESTRICT,
        CONSTRAINT ck_inv_count_details_physical CHECK (physical_stock >= 0),
        CONSTRAINT ux_inv_count_details_count_ingredient UNIQUE(count_id, ingredient_id)
      )
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS inv_count_details');
    await queryRunner.query('DROP TABLE IF EXISTS inv_counts');
    await queryRunner.query('DROP TABLE IF EXISTS inv_sale_consumption_details');
    await queryRunner.query('DROP TABLE IF EXISTS inv_sale_consumptions');
    await queryRunner.query('DROP TABLE IF EXISTS inv_movements');
    await queryRunner.query('DROP TABLE IF EXISTS inv_recipe_items');
    await queryRunner.query('DROP TABLE IF EXISTS inv_recipes');
    await queryRunner.query('DROP TABLE IF EXISTS inv_product_refs');
    await queryRunner.query('DROP TABLE IF EXISTS inv_ingredients');
  }
}
